### PR TITLE
[Fix] Overflow Issue for GridBlurredBackdrop

### PR DESCRIPTION
**Pull request by thetechie7**
When the window is resized there was an overflow on the right with this component. These 2 lines fix the issue!

### CODE REVIEW

**Comment by hauptrolle** [comment]
@thetechie7 Can u fix the merge conflicts int the yarn.lock?

**Comment by thetechie7** [comment]
> @thetechie7 Can u fix the merge conflicts int the yarn.lock?

Would you like me to delete the yarn.lock?

**Review by Utkarshn10 — CHANGES_REQUESTED** [review]
Hey @thetechie7 deleting the yarn.lock file and committing again should solve the issue. Hope this helps :)

**Comment by hauptrolle** [comment]
Please just remove the file from the commit. **Do not add an empty file**.

**Comment by thetechie7** [comment]
@hauptrolle issue should be fixed now sorry about that

**Review by hauptrolle — APPROVED** [review]

**Comment by hauptrolle** [comment]
@all-contributors please add @thetechie7 for code

**Pull request merged**
