### PR TITLE
feature(template): add new join our team form template

### LINKED ISSUE #45: Templates: Join our team
# Join our team
- Place in `Forms` category
- Designed with 1920 width
- Container: 2 columns centered, 640px each
- Title font: Work Sans Bold 80px
- Form title font: Work Sans Bold 48px
- Form description font: Inter Medium 16px
- Form input font: Inter Medium 16px
- Buttons font: Work Sans Bold 16px
- "YOU" label: Work Sans Bold 18px
- Avatars size: `80px` width x `80px` height
- Form background: `gray.50`
- Inputs background: `gray.100`
- Upload CV background: `gray.200`
- Form inputs text color: `gray.500`
- Title, Form title and Upload CV text color: `gray.800`
- "YOU" background: `gray.800`
- Avatars stroke: 3px outside, linear gradient, top-right to bottom-left, `red.400` at 0% to `pink.400` at 50%
- Golden avatar stroke: 3px outside, linear gradient, top-right to bottom-left, `orange.400` at 0% to `yellow.400` at 50%
- Corner gradient blur: `BLAST IT!`
- **Corner gradient overlays the title!**
- [Download assets](https://github.com/hauptrolle/chakra-templates/files/5832344/assets.zip)

Join our team

### PR DESCRIPTION
**Pull request by hauptrolle**
Fixed #45

### CODE REVIEW

**Review by lazarnikolov94 — CHANGES_REQUESTED** [review]
Woah! I love it! 🤩 It just needs a little fix on Dark Mode:

image

**Comment by hauptrolle** [comment]
Whoops. Will fix it tomorrow 😀

**Comment by hauptrolle** [comment]
Fixed. Please re-check. Should be ready for merge 💯

**Review by lazarnikolov94 — APPROVED** [review]
Looks great! 🙌

**Pull request merged**
