### PR TITLE
[feature]: add collapse sidebar like user requested on issue #155

### PR DESCRIPTION
**Pull request by TawalMc**
---
name: Collapse sidebar
---

# Feature 
Based on issue #155 , I create a sidebar that can expand and reduce when user (click) toggle the menu button. When it's a mobile support, it responds like a standard responsive sidebar so full fill the width of the screen.

### CODE REVIEW

**Review by hauptrolle — APPROVED** [review]

**Comment by hauptrolle** [comment]
Looks good. Maybe remove the yarn.lock from the commit so we don't have any conflicts.

**Comment by TawalMc** [comment]
Ok I'll do it and commit again. Thanks

**Comment by hauptrolle** [comment]
@TawalMc Still conflicts here. Can u rebase?

**Comment by hauptrolle** [comment]
Closed because of inactivity.

**Pull request closed without merging**
