### PR TITLE
Feature/track copy

### LINKED ISSUE #42: Analytics: Measure "Copy" button clicks
Add an event to measure the "Copy" button clicks. If possible, it'd be good if the "Manual Select & Copy" can be measured as well.

### PR DESCRIPTION
**Pull request by hauptrolle**
Fixes #42

### CODE REVIEW

**Review by lazarnikolov94 — APPROVED** [review]
LGTM! I made a little change, wrapped the `document.addEventListener('copy' ...` in a production mode so we don't send splitbee analytics events while in development.

**Comment by hauptrolle** [comment]
> LGTM! I made a little change, wrapped the `document.addEventListener('copy' ...` in a production mode so we don't send splitbee analytics events while in development.

Good idea! But the splitbee script is already only included in production mode. So this is not necessary 😄

**Comment by lazarnikolov94** [comment]
> > LGTM! I made a little change, wrapped the `document.addEventListener('copy' ...` in a production mode so we don't send splitbee analytics events while in development.
> 
> Good idea! But the splitbee script is already only included in production mode. So this is not necessary 😄

Yeah, but `window.splitbee.track` will throw an error because `window.splitbee` would be undefined. I thought about wrapping the contents of the `handleManualCopy` as well, but didn't want to repeat myself, so it's better we don't have a  copy listener at all.

**Comment by hauptrolle** [comment]
> > > LGTM! I made a little change, wrapped the `document.addEventListener('copy' ...` in a production mode so we don't send splitbee analytics events while in development.
> > 
> > 
> > Good idea! But the splitbee script is already only included in production mode. So this is not necessary 😄
> 
> Yeah, but `window.splitbee.track` will throw an error because `window.splitbee` would be undefined. I thought about wrapping the contents of the `handleManualCopy` as well, but didn't want to repeat myself, so it's better we don't have a copy listener at all.

Ohh, good catch! Did not think about that! 👍

**Pull request merged**
