### PR TITLE
feat: added new sidebar component - simple sidebar

### PR DESCRIPTION
**Pull request by sudoDeznit**
- Added a new subsection in Navigation called Sidebar
- Made a sidebar component - SImple SIdebar
Screenshot 2021-06-27 at 23 54 05
Screenshot 2021-06-27 at 23 54 35
Screenshot 2021-06-27 at 23 54 41

### CODE REVIEW

**Comment by sudoDeznit** [comment]
- Added new component sidebar with a header on main area

Screenshot 2021-06-28 at 13 16 15
Screenshot 2021-06-28 at 13 16 36

**Review by hauptrolle — CHANGES_REQUESTED** [review]
Hey @sudoDeznit Thank you so much for that merge request :)

Just one small note: The drawer close animation seems a little bit abrupt. Is this intended? It looks like the close animation is not running correct. Can you check this?

**Comment by sudoDeznit** [comment]
@hauptrolle is there any way I can control the transition speed ? I feel like close transition is happening but it's faster. Nothing in docs about that.

**Comment by hauptrolle** [comment]
> @hauptrolle is there any way I can control the transition speed ? I feel like close transition is happening but it's faster. Nothing in docs about that.

Damn did not know that. I will merge it this way. :)

**Comment by hauptrolle** [comment]
@all-contributors please add @sudoDeznit  for code

**Pull request merged**
